schema_version = "1.0.1"

id = "import_from_zip"
name = "Import From Zip"
version = "1.0.1"
tagline = "Import files directly from a ZIP archive"
maintainer = "Tsukino <151311004+tsukinokun@users.noreply.github.com>"
type = "add-on"

website = "https://github.com/tsukinokun/ImportFromZip"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 Tsukino",
]

tags = ["Import-Export"]
